"""Clickable recorded executions, with selection preserved across live refreshes."""

import streamlit as st

from hacknation_databricks.research.activity import activity_svg
from hacknation_databricks.research_views import label

_GRAPH_DEFINITION = dict(
    name="execution_graph",
    html='<div class="execution-graph"></div>',
    css="""
    .execution-graph {
        max-height: 480px;
        overflow: auto;
        border: 1px solid var(--st-border-color);
        border-radius: var(--st-base-radius);
        background: #ffffff;
    }
    .execution-graph svg { min-width: 860px; }
    [data-activity-key] { cursor: pointer; outline: none; }
    [data-activity-key]:hover > rect,
    [data-activity-key]:focus-visible > rect { stroke: #087e80; stroke-width: 4; }
    [data-activity-key][aria-pressed="true"] > rect { stroke-width: 4; }
    """,
    js="""
    export default function({ data, parentElement, setTriggerValue }) {
        const root = parentElement.querySelector('.execution-graph');
        const focused = parentElement.activeElement?.getAttribute('data-activity-key');
        const top = root.scrollTop;
        const left = root.scrollLeft;
        // SVG is generated by activity_svg; all archived labels/keys are escaped.
        if (root._svg !== data.svg) {
            root.innerHTML = data.svg;
            root._svg = data.svg;
            root.scrollTop = top;
            root.scrollLeft = left;
        }
        root.querySelector('svg').setAttribute('role', 'group');
        root.querySelectorAll('[data-activity-key]').forEach(box => {
            const key = box.getAttribute('data-activity-key');
            box.setAttribute('role', 'button');
            box.setAttribute('tabindex', '0');
            box.setAttribute('aria-label', data.labels[key]);
            box.setAttribute('aria-pressed', String(key === data.selected));
            const select = () => setTriggerValue('selected', key);
            box.onclick = select;
            box.onkeydown = event => {
                if (event.key === 'Enter' || event.key === ' ') {
                    event.preventDefault();
                    select();
                }
            };
            if (key === focused) box.focus({ preventScroll: true });
            if (data.follow && key === data.selected && root._selected !== key) {
                const rect = box.getBoundingClientRect();
                const bounds = root.getBoundingClientRect();
                root.scrollTop += rect.top - bounds.top - root.clientHeight / 2;
            }
        });
        root._selected = data.selected;
        return () => root.querySelectorAll('[data-activity-key]').forEach(box => {
            box.onclick = null;
            box.onkeydown = null;
        });
    }
    """,
)


def render_execution_graph(nodes, journal):
    """Only a key from the current trace can select a step; clicks pause live follow."""
    # Register once per session, after its runtime exists (also works in AppTest).
    if "_execution_graph_renderer" not in st.session_state:
        st.session_state["_execution_graph_renderer"] = st.components.v2.component(
            **_GRAPH_DEFINITION
        )
    scope = str(journal.directory.resolve())
    selection_key = f"execution-selection:{scope}"
    follow_key = f"execution-follow:{scope}"
    component_key = f"execution-graph:{scope}"
    by_key = {node.key: node for node in nodes}
    if st.session_state.get(selection_key) not in by_key:
        st.session_state[selection_key] = nodes[0].key
    follow = False
    if not journal.sealed:
        follow = st.toggle("Follow newest step", value=True, key=follow_key)
    if follow:
        st.session_state[selection_key] = nodes[-1].key
    selected = st.session_state[selection_key]

    def select_step():
        clicked = st.session_state.get(component_key, {}).get("selected")
        if isinstance(clicked, str) and clicked in by_key:
            st.session_state[selection_key] = clicked
            st.session_state[follow_key] = False

    graph = activity_svg(nodes, selected)
    st.session_state["_execution_graph_renderer"](
        key=component_key,
        data={
            "svg": graph,
            "selected": selected,
            "follow": follow,
            "labels": {
                node.key: f"{label(node.role)} · {node.stage} · {node.status}" for node in nodes
            },
        },
        on_selected_change=select_step,
    )
    return by_key[selected], graph
